repos:
  - repo: local
    hooks:
      - id: hatch-lint-check
        name: Hatch Lint Check
        entry: hatch
        args: ["run", "lint-check"]
        language: system
        types: [python]
      - id: hatch-lint-test
        name: Hatch Test
        entry: hatch
        args: ["run", "test"]
        language: system
        types: [python]
      - id: check-no-commit-in-remote-sample-data
        name: Check for committed files in remote_sample_data
        entry: bash .git/hooks/check_no_commit_in_remote_sample_data.sh
        language: system
        files: .*